// agent-ui/src/lib/components/inspector/InspectorPanel.svelte
<script lang="ts">
	import TabGroup from '$lib/components/common/TabGroup.svelte';
	import AgentTree from './AgentTree.svelte';
	import EventStream from './EventStream.svelte';
	import FilesPanel from './FilesPanel.svelte';
	import type { AgentEvent, AgentInfo } from '$lib/types';

	interface Props {
		tree: AgentInfo | null;
		events: AgentEvent[];
		sessionId: string;
		files: Record<string, string[]>;
	}

	let { tree, events, sessionId, files }: Props = $props();
	let activeTab = $state('tree');
</script>

<div class="flex h-full flex-col border-t border-[#2a2e3b] bg-[#161922]">
	<TabGroup
		tabs={[
			{ id: 'tree', label: 'Agent Tree' },
			{ id: 'events', label: 'Event Stream' },
			{ id: 'files', label: 'Files' }
		]}
		bind:activeTab
	>
		{#if activeTab === 'tree'}
			<AgentTree {tree} />
		{:else if activeTab === 'events'}
			<EventStream {events} />
		{:else if activeTab === 'files'}
			<FilesPanel {sessionId} {files} />
		{/if}
	</TabGroup>
</div>

// agent-ui/src/components/inspector/InspectorPanel.tsx
"use client";

import { TabGroup } from "@/components/common/TabGroup";
import { AgentTree } from "./AgentTree";
import { EventStream } from "./EventStream";
import { FilesPanel } from "./FilesPanel";
import type { AgentEvent, AgentInfo } from "@/lib/types";

interface InspectorPanelProps {
  tree: AgentInfo | null;
  events: AgentEvent[];
  sessionId: string;
  files: Record<string, string[]>;
}

export function InspectorPanel({ tree, events, sessionId, files }: InspectorPanelProps) {
  return (
    <div className="flex h-full flex-col border-t border-[#2a2e3b] bg-[#161922]">
      <TabGroup
        tabs={[
          { id: "tree", label: "Agent Tree", content: <AgentTree tree={tree} /> },
          { id: "events", label: "Event Stream", content: <EventStream events={events} /> },
          { id: "files", label: "Files", content: <FilesPanel sessionId={sessionId} files={files} /> },
        ]}
      />
    </div>
  );
}
