// agent-ui/src/components/chat/MessageList.tsx
"use client";

import { useRef, useEffect } from "react";
import { MessageItem } from "./MessageItem";
import type { Message } from "@/lib/types";

export function MessageList({ messages }: { messages: Message[] }) {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  return (
    <div className="flex flex-1 flex-col gap-3 overflow-y-auto p-5">
      {messages.map((msg) => (
        <MessageItem key={msg.id} msg={msg} />
      ))}
      <div ref={bottomRef} />
    </div>
  );
}

// agent-ui/src/lib/components/chat/MessageList.svelte
<script lang="ts">
	import MessageItem from './MessageItem.svelte';
	import type { Message } from '$lib/types';

	interface Props {
		messages: Message[];
	}

	let { messages }: Props = $props();
	let bottomEl = $state<HTMLDivElement | null>(null);

	$effect(() => {
		// Track messages to auto-scroll
		messages;
		bottomEl?.scrollIntoView({ behavior: 'smooth' });
	});
</script>

<div class="flex flex-1 flex-col gap-3 overflow-y-auto p-5">
	{#each messages as msg (msg.id)}
		<MessageItem {msg} />
	{/each}
	<div bind:this={bottomEl}></div>
</div>
